services:
  mysql:
    image: mysql:8.4
    container_name: sksiskur-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sksiskur
    ports:
      - "3306:3306"
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_turkish_ci
    volumes:
      - sksiskur-mysql:/var/lib/mysql

volumes:
  sksiskur-mysql:
